### ISSUE TITLE
java.lang.ClassNotFoundException: com.sun.deploy.uitoolkit.impl.fx.HostServicesFactory on openjfx

### ISSUE THREAD

**Issue by walec51** [thomasdarimont/spring-labs#11]
I get this when I try to run the basic app from you tutorial:

java.lang.ClassNotFoundException: com.sun.deploy.uitoolkit.impl.fx.HostServicesFactory
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at com.sun.javafx.application.HostServicesDelegate.lambda$getInstance$0(HostServicesDelegate.java:52)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.HostServicesDelegate.getInstance(HostServicesDelegate.java:45)
	at javafx.application.HostServices.<init>(HostServices.java:52)
	at javafx.application.Application.getHostServices(Application.java:334)
	at de.felixroske.jfxsupport.AbstractJavaFxApplicationSupport.start(AbstractJavaFxApplicationSupport.java:85)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$106(LauncherImpl.java:863)
	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$119(PlatformImpl.java:326)
	at com.sun.javafx.application.PlatformImpl.lambda$null$117(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$118(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$null$450(GtkApplication.java:139)
	at java.lang.Thread.run(Thread.java:748)

Problem seams identical to: https://github.com/Qabel/qabel-desktop/issues/420

**Comment by walec51** [comment]
ups, wrong project, I used de.roskenet:springboot-javafx-support
:o)
